name: Auto Commit Changes

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  commit-changes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Auto Commit and Push
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions Bot"
          git add .
          git commit -m "Auto-update from ChatGPT changes" || echo "No changes to commit"
          git push
